# -*- coding: utf-8 -*-
"""day2 pract.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HUV8Vi34CwjeUT0i2dE7tuXDynl0hLgR
"""

#Extract all the numbers.
text1 = "There are 3 cats, 14 dogs, and 1 turtle in the house."

#Extract all valid emails.
text2 = "Send emails to: user1@gmail.com, support@company.org, and fake@.com"

#Extract valid Egyptian mobile numbers (starting with 010, 011, 012, 015).
text3 = "Contact us at 01012345678 or 01599999999 or 01987654321 or 010-20541078"

#Remove all punctuation and print the clean text.
text4 = "Hello, world! Let's clean this: text. Right?"

#Extract all hashtags.
text5 = "Follow us for #updates, #PythonTips and #100DaysOfCode!"

#Split Paragraph into Sentences
text6 = "Hello! How are you doing? I hope you're enjoying regex. Let's practice more."

#Validate Passwords
passwords = ["pass123", "Secure1", "12345678", "Password123", "noDigitHere"]

#Remove HTML Tags
html_text = "<div><h1>Welcome</h1><p>This is a <b>test</b> string.</p></div>"

#Extract Dates
date_text = "Important dates: 29-06-2025, 01/01/2024, and 2024.12.31."

#Validate Dataset of User Info
users = [
    {"email": "user1@gmail.com", "phone": "01012345678", "password": "Strong123"},
    {"email": "fakeemail.com", "phone": "01600000000", "password": "weak"},
    {"email": "name@domain.co", "phone": "01298765432", "password": "Pass1234"},
]